---
title: "Lenguajes de Marcas: LaTeX | LMTW"
author: "Víctor Peinado"
date: "10 de marzo de 2015"
output: rmarkdown::tufte_handout
---


# Introducción a LaTeX

- LaTeX no es un procesador de textos WYSIWYG como MS Word o el Writer de
  OpenOffice.
- Es más bien un *lenguaje de programación* que permite escribir un texto de
  forma estructurada y convertirlo en documentos para ser leídos o impresos con una gran calidad tipográfica.
- LaTeX combina la sencillez de edición, la calidad tipográfica y la facilidad para garantizar una buena estructura y organización del documento, todo esto de manera casi automática. 
- El contenido del texto que se edita no es el resultado final. 
- Antes de visualizar el resultado final es necesario convertir el código LaTeX
  en un formato visualizable como PS, PDF o HTML (pero también, RTF o DOC).


# Cambio de chip

- ¿Qué ventajas tiene este modo de producir documentos frente a los sistemas
  WYSIWYG?
- Pensemos en elaborar un documento único de 500 páginas compilado a partir de
  una docena de capítulos diferentes y separados en distintos ficheros, pero
  mostrando índices únicos de capítulos, tablas e imágenes, bibliografía, etc.
- LaTeX fuerza al autor a ser estructurado. 
- No tiene más que concentrarse en el contenido del documento y en señalar unas cuantas instrucciones para que LaTeX haga lo que las instrucciones le indiquen: hacer una portada, un índice de contenidos, poner las notas a pie de página, insertar una imagen, etc. 


En lugar de seleccionar manualmente el tipo de fuente que usaremos para el título de una sección, su tamaño y su estilo (y de recordar todo esto para cuando se llegue el momento de iniciar otra sección), en LaTeX sólo tenemos que indicarle que dentro del documento que en un determinado lugar se inicia una sección.

    !latex
    \section{Nombre de la sección}
    
Y con ello obtendremos un verdadero título de sección con todo y su numeración, con independencia de las secciones que podamos insertar antes o después de esta instrucción de estructura del texto.


# Escritura de documentos en LaTeX

1. Para [escribir documentos en LaTeX](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Datos_preliminares/La_escritura_en_LaTeX) es necesario utilizar un editor de textos capaz de crear ficheros en formato `.tex`.

2. El archivo fuente `.tex` contendrá todas las instrucciones que serán procesadas por LaTeX para producir un archivo de salida.

3. Para crear el fichero de salida, tenemos que *compilar* el fichero fuente
   `.tex`. 

4. Por ejemplo, si hemos creado el archivo `ejemplo.tex`, y queremos compilarlo en formato PDF, abrimos una terminal o símbolo del sistema, nos ubicamos en la dirección donde se encuentre nuestro fichero y escribimos:

    `pdflatex ejemplo.tex`



# Instalación

- [Instalación en
  Windows](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Datos_preliminares/Instalaci%C3%B3n_en_MS_Windows).
- [Instalación en MacOS](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Datos_preliminares/Instalaci%C3%B3n_en_OS_X).
- [Instalación en Linux](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Datos_preliminares/Instalaci%C3%B3n_en_Linux).

Pero nosotros no vamos a instalar nada, vamos a hacer todas las pruebas usando
herramientas web para editar LaTeX. 

- [writeLaTex](https://www.writelatex.com)
- [spandex.io](https://spandex.io)


# Estructura de un documento LaTeX

La [estructura de un documento LaTeX](http://es.wikibooks.org/wiki/Manual_de_LaTeX/La_estructura_de_un_documento_en_LaTeX/El_pre%C3%A1mbulo_y_el_cuerpo_del_documento) se divide en **preámbulo** y **cuerpo de texto**.

En el **preámbulo** se escriben las instrucciones fundamentales que indican a LaTeX qué [clase de documento](http://es.wikibooks.org/wiki/Manual_de_LaTeX/La_estructura_de_un_documento_en_LaTeX/Clases_de_documento_y_algunos_paquetes_comunes) se va a escribir (*article, book, report, slides*, etc.) y qué características va a tener éste:

    !latex
    \documentclass{article}

Además de indicar la clase de documento que queremos para nuestro texto, debemos indicar los paquetes que vamos a necesitar:

    !latex
    \usepackage{paquete}


# Estructura de un documento LaTeX

El **cuerpo del documento** inicia con la instrucción

    !latex
    \begin{document}

y culmina con la instrucción:

    !latex
    \end{document}


Todo lo que se escriba con posterioridad a esta instrucción será ignorado y no se compilará.

El cuerpo del documento consiste en prácticamente todo lo que aparecerá en nuestro texto:


# Escribiendo texto

- [Espacios](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Espacios)
- [Caracteres especiales](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Caracteres_especiales)
- [Tamaños, estilos y tipos de letra](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Tama%C3%B1os,_estilos_y_tipos_de_letra)
- [Alineación de texto](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Alineaci%C3%B3n_del_texto)
- [Portadas de
  documento](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Portada_del_documento)
- [Capítulos y secciones](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Cap%C3%ADtulos_y_secciones)
- [Referencias](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Referencias)
- [Notas a pie](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Notas_al_pie)
- [Listas](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Entornos_de_enumeraci%C3%B3n)
- [Tablas](http://es.wikibooks.org/wiki/Manual_de_LaTeX/Escribiendo_texto/Tablas)


# LaTeX para Lingüística

- [Paquetes de LaTeX para
  Lingüística](http://en.wikibooks.org/wiki/LaTeX/Linguistics).
- [The LaTeX for Linguists Home Page](http://www.essex.ac.uk/linguistics/external/clmt/latex4ling)
- [TIPA: a System for Processing Phonetic Symbols in LaTeX](http://www.tug.org/tugboat/tb17-2/tb51rei.pdf)


# Referencias

- [The Not So Short Introduction to LaTeX](https://cv2.sim.ucm.es/moodle/mod/resource/view.php?id=863033)
- [Manual de LaTeX](http://es.wikibooks.org/wiki/Manual_de_LaTeX).
- [A Guide to LaTeX](http://en.wikibooks.org/wiki/LaTeX).
- [LaTeX for Mathematics](http://en.wikibooks.org/wiki/LaTeX/Mathematics).

